#!/bin/bash

MYSQL_TAG="5.6"
sudo docker pull mysql:$MYSQL_TAG
docker run --restart always -d --name mysql$MYSQL_TAG -v /opt/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mysql5.6 -p 3306:3306 mysql:$MYSQL_TAG
